name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: "us-west-2"
  ENVIRONMENT_STAGE: "dev"

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
        shell: bash
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ vars.AWS_REGION }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)

          pwd
          ls -alt
          echo $GITHUB_WORKSPACE
          ls -alt $GITHUB_WORKSPACE

          echo "Running Terraform Init"
          terraform init -backend-config="bucket=${{vars.TF_STATE_BUCKET}}" -backend-config="key=dev/terraform.tfstate" -backend-config="region=${{vars.AWS_REGION}}" 

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false -var-file=terraform.tfvars ${{ env.CREATE_CLUSTER_OVERRIDE }}
        env:
          CREATE_CLUSTER_OVERRIDE: ${{ github.ref == 'refs/heads/main' && '-var=create_cluster_enabled=true' || '' }}

      # # Build infrastructure according to Terraform configuration files
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false -var-file=${ENVIRONMENT_STAGE}.tfvars ${{ env.CREATE_CLUSTER_OVERRIDE }}
      #   env:
      #     CREATE_CLUSTER_OVERRIDE: ${{ github.ref == 'refs/heads/main' && '-var=create_cluster_enabled=true' || '' }}



  